In [26]:
import torch

In [27]:
x = torch.arange(0,4.0,1,requires_grad=True) # 
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [28]:
print(x.grad)

None


In [29]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

调用反向传波函数来自动计算梯度

In [30]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [31]:
y = sum(x)
x.grad

tensor([ 0.,  4.,  8., 12.])

保存之前计算的梯度,需要手动清空

In [32]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [33]:
y = sum(x)
y.backward()
x.grad

tensor([1., 1., 1., 1.])