In [1]:
import torch
from torch.distributions import multinomial # 多项分布

probs是等概率分布时的概率

In [2]:
probs = torch.ones(6) / 6
probs

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])

根据probs随机取样,看取到的是第几个

In [3]:
for i in range(5):
    print(multinomial.Multinomial(1,probs).sample())

tensor([0., 0., 0., 0., 1., 0.])
tensor([0., 0., 0., 0., 1., 0.])
tensor([0., 0., 0., 1., 0., 0.])
tensor([0., 0., 1., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 1.])


扩大取样范围

In [4]:
count = 10**5
res = multinomial.Multinomial(count,probs).sample()

In [5]:
res

tensor([16543., 16825., 16702., 16477., 16767., 16686.])

In [6]:
probs - res/count

tensor([ 0.0012, -0.0016, -0.0004,  0.0019, -0.0010, -0.0002])

In [7]:
abs(probs - res/count)

tensor([0.0012, 0.0016, 0.0004, 0.0019, 0.0010, 0.0002])

In [8]:
abs(probs - res/count)<1e-3

tensor([False, False,  True, False, False,  True])