In [25]:
from torch import nn
import torch

In [26]:
seed = 59
torch.manual_seed(seed)

In [27]:
t = torch.randint(0,10,(2,3,4))
t

tensor([[[3, 6, 3, 7],
         [3, 5, 7, 1],
         [2, 5, 1, 4]],

        [[7, 9, 1, 2],
         [5, 2, 9, 6],
         [3, 2, 4, 7]]])

In [28]:
flat = nn.Flatten()
res = flat(t)

In [29]:
res

tensor([[3, 6, 3, 7, 3, 5, 7, 1, 2, 5, 1, 4],
        [7, 9, 1, 2, 5, 2, 9, 6, 3, 2, 4, 7]])

In [30]:
res.shape

torch.Size([2, 12])

In [31]:
flat = nn.Flatten(0,1)
res = flat(t)

In [32]:
res

tensor([[3, 6, 3, 7],
        [3, 5, 7, 1],
        [2, 5, 1, 4],
        [7, 9, 1, 2],
        [5, 2, 9, 6],
        [3, 2, 4, 7]])

In [33]:
res.shape

torch.Size([6, 4])

In [34]:
flat = nn.Flatten(0,2)
res = flat(t)

In [35]:
res

tensor([3, 6, 3, 7, 3, 5, 7, 1, 2, 5, 1, 4, 7, 9, 1, 2, 5, 2, 9, 6, 3, 2, 4, 7])

In [36]:
res.shape

torch.Size([24])