In [1]:
import torchvision
import torch

/home/whr-pc-ubuntu/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/whr-pc-ubuntu/.local/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")


# 无ToTensor

In [2]:
transform = torchvision.transforms.Compose([
    # torchvision.transforms.ToTensor(),
])

data_dir = '/home/whr-pc-ubuntu/code/dataset'
server_train_data = torchvision.datasets.MNIST(data_dir, train=True, download=True, transform=transform)
server_test_data = torchvision.datasets.MNIST(data_dir, train=False, download=True, transform=transform)

MNIST数据集原始值的范围是[0,255]

首先不加transform，读入的是PIL.Image.Image，data属性中值的范围是[0,255]

In [3]:
type(server_train_data[0][0])

PIL.Image.Image

In [4]:
server_train_data[0][0]

In [12]:
server_train_data[0][1]

5

In [5]:
server_train_data.data[0]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
          18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

# 有ToTensor

In [6]:
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
])

data_dir = '/home/whr-pc-ubuntu/code/dataset'
server_train_data = torchvision.datasets.MNIST(data_dir, train=True, download=True, transform=transform)
server_test_data = torchvision.datasets.MNIST(data_dir, train=False, download=True, transform=transform)

In [7]:
type(server_train_data[0][0])

torch.Tensor

经过ToTensor这个transform后，类型变成torch.Tensor，范围是[0,1]：

In [8]:
server_train_data[0][0]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

但是data属性中，值的范围仍然是[0,255]

In [9]:
server_train_data.data[0]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
          18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

# 均值与方差

## 均值

### 遍历

In [47]:
train_mean = 0
for x,y in server_train_data:
    # train_mean += x.mean()
    train_mean += x.sum()
train_mean = train_mean / len(server_train_data) / 28 / 28

In [48]:
train_mean

tensor(0.1307)

In [49]:
train_mean = 0
for x,y in server_train_data:
    train_mean += x.mean()
train_mean = train_mean / len(server_train_data)

In [50]:
train_mean

tensor(0.1307)

### 除以255

In [ ]:
(server_train_data.data / 255).mean()

tensor(0.1307)

## 方差

### 遍历

In [51]:
train_std = 0
for x,y in server_train_data:
    train_std += torch.pow(x-train_mean,2).sum()

torch.sqrt(train_std / len(server_train_data) / 28 / 28)


tensor(0.3081)

In [55]:
train_std = 0
for x,y in server_train_data:
    train_std += x.var()

torch.sqrt(train_std / len(server_train_data))

tensor(0.3052)

如果直接用该对象求均值，需要遍历、累加，但不需要除以255，因为本身范围就是[0,1]

如果用data属性求均值，直接可以用mean()函数，但需要除以255

In [11]:
(server_train_data.data / 255).std()

tensor(0.3081)

# 标准正态分布(有normalize)

获得上面这两个数后，可以知道MNIST符合(0.1307,0.3081)的正态分布，然后可以通过$\frac{x-u}{\sigma}$转为标准正态分布。

In [13]:
transform = torchvision.transforms.Compose([
        torchvision.transforms.ToTensor(),
        torchvision.transforms.Normalize((0.1307,),(0.3081,)),
    ])

In [14]:
train_dataset = torchvision.datasets.MNIST(
    data_dir,
    True,
    transform,
    download=True
    )

In [16]:
train_dataset[0][0]

tensor([[[-0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242],
         [-0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242],
         [-0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242],
         [-0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242,
          -0.4242, -0.4242, -0.4242, -0.4242, -0

再次计算均值与方差, 应该是(0,1)

In [59]:
train_mean = 0
for x,y in train_dataset:
    train_mean += x.mean()

train_mean = train_mean / len(train_dataset)

In [60]:
train_mean

tensor(-0.0001)

In [61]:
train_std = 0
for x,y in train_dataset:
    train_std += torch.pow((x-train_mean),2).sum()

train_std = torch.sqrt(train_std/len(train_dataset)/28/28)

In [62]:
train_std

tensor(1.0000)