In [1]:
import torch
import copy
from torch import nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_1 = nn.Linear(in_features=2, out_features=1)
    def forward(self, input):
        x = torch.relu(self.linear_1(input))
        return x


In [2]:
model_1 = Model()
model_2 = copy.deepcopy(model_1)


In [3]:
for name, param in model_1.named_parameters():
    print(f"model 1, {name}, {param}")

model 1, linear_1.weight, Parameter containing:
tensor([[-0.0183,  0.1212]], requires_grad=True)
model 1, linear_1.bias, Parameter containing:
tensor([-0.0386], requires_grad=True)


In [4]:
for name, param in model_2.named_parameters():
    print(f"model 2, {name}, {param}")

model 2, linear_1.weight, Parameter containing:
tensor([[-0.0183,  0.1212]], requires_grad=True)
model 2, linear_1.bias, Parameter containing:
tensor([-0.0386], requires_grad=True)


In [5]:
for name, param in model_1.named_parameters():
    param.data = param.data * 2

In [6]:
for name, param in model_1.named_parameters():
    print(f"model 1, {name}, {param}")

model 1, linear_1.weight, Parameter containing:
tensor([[-0.0366,  0.2424]], requires_grad=True)
model 1, linear_1.bias, Parameter containing:
tensor([-0.0772], requires_grad=True)


In [7]:
for name, param in model_2.named_parameters():
    print(f"model 2, {name}, {param}")

model 2, linear_1.weight, Parameter containing:
tensor([[-0.0183,  0.1212]], requires_grad=True)
model 2, linear_1.bias, Parameter containing:
tensor([-0.0386], requires_grad=True)
